# Site settings
title: Becca Nelson
email: beccanelsonmakesthings@gmail.com
description: "Thoughts on life, creativity, and technology."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://beccanelson.is" # the base hostname & protocol for your site
twitter_username: beccaliz
github_username:  beccanelson
facebook_username: beccanelsonwriter
instagram_username: beccawonders
disqus_username: beccanelsongithub
permalink: /:title
gems: [jekyll-paginate]
paginate: 8
paginate_path: "/developing/page:num/"
navigation:
  - title: Home
    url: /
  - title: Blog
    url: /developing
  - title: Contact
    url: /contact
  - title: Projects
    url: /making-things
  - title: Résumé
    url: /awesome

# Build settings
markdown: kramdown
